import type { Metadata } from "next";

import "./globals.css";

export const metadata: Metadata = {
  title: "Next Demo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header className="bg-green-500 text-center p-4">Root Layout</header>
        <main> {children}</main>
      </body>
    </html>
  );
}
